### ISSUE TITLE
Buffer clavier

### ISSUE THREAD

**Issue by Yamakaky** [FrOSt-Foundation/FrOSt#1]
A vérifier : il faudrait vider le buffer du clavier après avoir utilisé cette interruption matérielle pour éviter une contamination de l’interruption matérielle 1 :

2 | Set C register to 1 if the key specified by the B register is pressed, or
  | 0 if it's not pressed

1 | Store next key typed in C register, or 0 if the buffer is empty

**Comment by L3nn0x** [comment]
On a pas de buffer clavier. Les fonctions retournent directement la valeur dans un registre.
