### ISSUE TITLE
Réserver l'utilisation des HWI aux drivers ?

### ISSUE THREAD

**Issue by azertyfun** [FrOSt-Foundation/FrOSt#10]
Le scheduler et l'interruptHandler utilisent tous les deux des HWI. Ce serait pas mieux de tout faire passer par le hardware ? Ca rendrait la maintenance plus facile...

**Comment by Yamakaky** [comment]
(tu parles bien de faire en sorte que les drivers soient les seuls à utiliser les hwi ?)
C'est ce que j'avais proposé il y a un moment, mais l'OS est tombé en léthargie entre temps XD

**Comment by azertyfun** [comment]
Oui voilà. Par exemple le scheduler utilise des HWI, mais ce serait plus propre d'utiliser ceux du driver, quitte à en implémenter de nouveaux.

**Comment by Yamakaky** [comment]
Cool. Pour info, les emplacement avec des hwi non autorisés :
kernel/InterruptHandler.dasm:192:hwi [id_clavier]
kernel/Scheduler.dasm:138:hwi [id_clock]
kernel/Scheduler.dasm:210:hwi [id_clavier]

**Comment by azertyfun** [comment]
T'inquiètes je sais utiliser l'onglet search :p 
Je corrige l'handler mais ce sera à Faërie de s'occuper du scheduler, parce que c'est un peu un bordel non-commenté (et encore, je l'ai indenté xD)

**Comment by L3nn0x** [comment]
Mais nan ! Mais nan ! De toute façon je vais refaire le shced

**Comment by Yamakaky** [comment]
Je préfère `grep -inR hwi` à la racine ^^

**Comment by azertyfun** [comment]
Ouais mais tu vois je travaille sous windows tu vois et la fonction search marche aussi bien :p 
@FaerieFrOSt Ok mais alors regarde mon iddue sur les conventions de nommage :p

**Comment by Yamakaky** [comment]
Je sais ^^

**Comment by Yamakaky** [comment]
Done, apparemment.

**Comment by L3nn0x** [comment]
Je vais expliquer une bonne fois pour toutes : les routines qui ont besoin de vitesse seront épargnées par tout ce qui est "conventions". Le but est d'obtenir un code rapide et léger, pas un code joli. Donc adios les jsr dans les fonctions critiques.
