### ISSUE TITLE
SImplifier le gestionnaire de périphériques

### ISSUE THREAD

**Issue by azertyfun** [FrOSt-Foundation/FrOSt#11]
Ca serait pas mal de simplifier le gestoinnaire de périphériques, car là à cause de la gestion des périphériques multiples ce n'est pas du tout clair. Il faudrait garder la fonction <code>detection_and_init_periphs</code> mais faire une seule fonction par driver qui gère l'initialisation _et_ la gestion des périphs multiples, ça serait plus simple à maintenir.

**Comment by Yamakaky** [comment]
Encore une fois, c'était une de mes suggestions avant la léthargie de l'OS ^^
Tant qu'on y est, il faudrait aussi mettre les variables type id_keyboard dans le driver concerné, et pas dans kernel/DAT.

De plus, il faudrait qu'on utilise les `.define ID <truc>`, au lieu de variables en dur. Ce serait plus facile à modifier.

**Comment by azertyfun** [comment]
Les IDs sont modifiées au court de l'exécution, donc si on parle de defines comme je les connait ça le fera pas trop :p 
Par contre je suis pas trop pour éparpiller les IDs, c'est plus simple de faire un seul fichier DAT.dasm avec des grands blocs de commentaires qui séparent en catégorie, genre comme ça : 

<pre>; ----------------------
; Kernel
; ----------------------
; Addresses du hardware : 
:id_clavier DAT 0
:id_ecran DAT 0
;Police d'écriture
:font DAT 0x1234, 0x1234, 0x1234</pre>

Le problème c'est qu'on est souvent confrontés à des labels dont on ne sait pas si ils sont dans le DAT.dasm ou dans le fichier même, c'est quand même très con.

**Comment by Yamakaky** [comment]
Justement, vu que les drivers sont les seuls à gérer les hwi et les id, autant y mettre les id, comme ça tout sera au même endroit.

Je pensait aux `.define` pour les constantes, type `SCREEN_WIDTH`

**Comment by azertyfun** [comment]
Aaaah oui du coup tu peux faire ça :p 
Sinon je déplace les DATs vers le dossier kernel comme ça ça sera fait :)
