### ISSUE TITLE
Conventions de nommage et commentaires

### ISSUE THREAD

**Issue by azertyfun** [FrOSt-Foundation/FrOSt#12]
Il faudrait rajouter des conventions de nommages pour les fonctions, les variables et les fichiers parce que là en fonction du codeur ça donne des trucs radicalement différents.
Pour les routines il faudrait faire ça : 

<pre>:maRoutine
    SET B, 1
    SET B, 2
    :maRoutine_sousRoutine
        ADD B, 1
        MUl B, 5
        :maRoutine_sousRoutine_loop
            ADD B, 1
            IFN B, 100
            SET PC, maRoutine_sousRoutine_loop
    SET PC, POP</pre>

C'est beaucoup plus clair pour s'y retrouver dans les routines et sous-routines, parce que sinon on ne sait pas quoi appartient à qui ^^

Ensuite, et c'est une convention universelle, un nom de variable commence par une minuscule. Pareil pour un fichier, parce que aux dernières nouvelles on ne fait pas de POO :p 
Faire une routine "Sched_AddProc" c'est pas du tout correct, ça devrait être "sched_addProc", qui est plus lisible et plus simple à taper ! ^^

Voilàvoilà

Ensuite faudrait vraiment penser à commenter le code, surtout que certains noms de variables de sont pas très explicites. Le scheduler est totalement incompréhensible par exemple. Le registre A est utilisé tout du long mais sans commentaire on doit passer 2 min à se demander à quoi il peut bien correspondre à un endroit précis de la routine.

**Comment by Yamakaky** [comment]
C'est marrant, tu met en place toutes les idées que j'avais eu avant la Grande Léthargie XD

Petit point de détail : on met les instructions en majuscule ou pas ? Comparaison : 

``` dasm
:maRoutine
    SET B, 1
    SET B, 2
    :maRoutine_sousRoutine
        ADD B, 1
        MUl B, 5
        :maRoutine_sousRoutine_loop
            ADD B, 1
            IFN B, 100
            SET PC, maRoutine_sousRoutine_loop
    SET PC, POP
```

``` dasm
:maRoutine
    set B, 1
    set B, 2
    :maRoutine_sousRoutine
        add B, 1
        mul B, 5
        :maRoutine_sousRoutine_loop
            add B, 1
            ifn B, 100
                    set PC, maRoutine_sousRoutine_loop
    set PC, POP
```

**Comment by azertyfun** [comment]
Perso je les met en majuscules mais si c'est en minuscules c'est pas trop grave. De toute façon avant une release c'est tout à fait possible de faire un script à la con qui met tout en majuscules.

**Comment by Yamakaky** [comment]
oui, pas faux. Y a même des hooks git pour ça ! J'y pense à l'instant, c'est tout à fait possible d'avoir un hook qui convertit tout en maj/min, comme pour la gestion de CRLF/LF. Je me lance ?

**Comment by azertyfun** [comment]
Mhmm gaffe quand même, ça risque de modifier PUSH_regs et autres conneries du genre, on fera ça une bonne fois avant de faire une release je crois.

**Comment by Yamakaky** [comment]
Autant utiliser les outils à notre disposition ^^
Perso je sais pas trop, je trouve les min un peu plus lisible

Vaut mieux pas, ça ferai plein de commis pour rien

**Comment by azertyfun** [comment]
Si je le met en majuscules c'est surtout par habitude ^^
Tant que c'est pas SeT, xOR ou Bor tout va bien :p

**Comment by Yamakaky** [comment]
C'est surtout pour une homogénéité du code.
Je propose la norme suivante : 
- les instructions en minuscule
- les registres + POP/PUSH en majuscule
- les labels en minuscule type maRoutine_sousRoutine_loop, pour les distinguer des registres
- un espace après la virgule

Exemple : 

``` dasm
set A, B
add label, 5   ; oui, je sais, ça compile pas ^^
add PUSH, POP ; équivalent à mul [SP], 2, sauf erreur ?
```

**Comment by azertyfun** [comment]
Ca me semble bien :p

**Comment by Yamakaky** [comment]
Ok, je vais update le README.

**Comment by L3nn0x** [comment]
Moi je laisse pas d'espace et push/pop sont en minuscules. On peut pas faire comme ça plutôt ?

**Comment by azertyfun** [comment]
Ben non parce que c'est moche et pas lisible, espèce de feignant xD
Au pire tu fait ctrl+f tu pourras remplacer push par PUSH à la fin :p

**Comment by L3nn0x** [comment]
mais c'est long de taper un espace en plus après la virgule...

**Comment by azertyfun** [comment]
Euh... WAT
Et puis même ça marche aussi le chercher/remplacer xD

**Comment by Yamakaky** [comment]
C'est bien ce que je pensait : c'est un fleimard ^^

**Comment by L3nn0x** [comment]
Bon, bon, je me ferai un script, voilà. Content ?

**Comment by azertyfun** [comment]
Wi xD

**Comment by Yamakaky** [comment]
Regarde du côté des git hooks, comme ça il sera lancé automatiquement à chaque commit.

**Comment by L3nn0x** [comment]
Ok.
