### ISSUE TITLE
Quelle est la variable counter ?

### ISSUE THREAD

**Issue by azertyfun** [FrOSt-Foundation/FrOSt#13]
C'est quoi la variable counter dans le scheduler ? J'ai un peu du mal à cerner son utilité ^^
Pareil pour total_prio d'ailleurs.

**Comment by Yamakaky** [comment]
Faëriiiiiiiie ?

**Comment by Yamakaky** [comment]
Ce serait pas le nombre de programmes qui tournent ?

**Comment by azertyfun** [comment]
Ah c'est fort possible, je croyais que c'était une autre var. Mais total_prio c'est quoi ? ^^'

**Comment by Yamakaky** [comment]
Faut demander à Faërie…

**Comment by azertyfun** [comment]
Je suppose que tu ne sais pas non plus ce que c'est que KER_SP ? Vive les noms explicites :trollface:

**Comment by azertyfun** [comment]
Autre chose, je comprend pas bien ce bout de code (scheduler.dasm, lignes 69 à 72) : 

<pre>set A, PEEK
set [Z + 0x2F], [SP + 1]
add Z, 0x26
set [A + 3], Z</pre>

**Comment by Yamakaky** [comment]
…
Faërie mind not found.

**Comment by L3nn0x** [comment]
Here comes Faërie's mind !

La variable counter sert à compter le nombre de programmes. La variable total_prio retient la priorité totale cumulée de tous les programmes. Et le bout de code arrive dans le prochain message.

**Comment by L3nn0x** [comment]
Ker_sp est la sauvegarde de la pile kernel.

**Comment by L3nn0x** [comment]
On récupère l'adresse de la structure process en cours de remplissage dans A. On met l'adresse du programme que l'on va exécuter à la fin de la mémoire que l'on vient d'allouer et on met la prochaine valeur de sp dans la structure. (La mémoire en Z étant la pile du programme.

**Comment by azertyfun** [comment]
Euké thanks je finit de commenter le scheduler du coup.
