### ISSUE TITLE
L'écran ne s'allume pas

### ISSUE THREAD

**Issue by azertyfun** [FrOSt-Foundation/FrOSt#14]
Il semblerait qu'il y aie un problème avec le mappage de l'écran, je vais tenter de debug ça.

**Comment by azertyfun** [comment]
Bon, il y a bien du texte dans la RAM, l'adresse de l'écran pointe bien vers cet endroit de la RAM, le HWI se passe bien correctement mais il ne s'allume pas.

**Comment by Yamakaky** [comment]
tu as bien créé un écran dans devcpu, le relié au cpu et lier l'affichage à l'écran ?

**Comment by L3nn0x** [comment]
C'est étrange.

**Comment by azertyfun** [comment]
Parce que vous vous arrivez à le lancer ?
Sinon tout aussi étrangement à l'adresse où est mappée l'écran y'a bien des trucs mais apparemment c'est pas du text ASCII ._.

**Comment by L3nn0x** [comment]
Avec le DevKit, l'OS fonctionnait. Donc c'est bizarre qu'on ait rien ici. Je vais faire des tests.

**Comment by azertyfun** [comment]
Et il marche chez toi Yama ? Ca serait con quand même.
Et la même configuration du DCPU fait tourner à merveille mon OS, donc y'a peu de chances que ça vienne de là.

**Comment by Yamakaky** [comment]
2 sec je teste

**Comment by azertyfun** [comment]
Oui bon je viens juste de me rappeler que si le HExView m'affiche pas de texte aSCII il est formaté c'est normal.
Mais en fait l'écran ne s'allume pas, c'est de là que vient le problème. Or, c'est censé le faire dès que on le VRAM. C'est donc le gestionnaire des périphs qui enregistre pas la bonne ID, je vias voir ça.

**Comment by azertyfun** [comment]
OUI CA MARCHE ! Je fais un commit et un push :D :dancer:

**Comment by L3nn0x** [comment]
Cool.

**Comment by azertyfun** [comment]
Mhmm par contre j'arrive pas à faire marcher le keyboard ^^'

**Comment by L3nn0x** [comment]
Ça doit être le gestionnaire qui bug aussi. (Ce sera pareil pour l'horloge et le lecteur de cartes.)

**Comment by Yamakaky** [comment]
Y a une issue à ce sujet je crois

**Comment by Yamakaky** [comment]
Ça marche chez vous ?

**Comment by azertyfun** [comment]
Chez moi ça marche, si tu as fait un pull ça devrait aller ^^
Sinon oui je suis d'accord, en fait l'ID des périphériques est très longue (celle de l'écran est 0x1c6c8b36). Vous aviez donc comparé J à 1c6c. OR, il faut comparer à la fin du nombre, 8b36 ! C'est très con en fait.
Par contre le clavier devrait marcher si je met 0x7406 :(

**Comment by L3nn0x** [comment]
N'oublie pas l'horloge, ça fonctionne pas sinon il me semble. (Ou alors c'est un bug dans le sched quand vous l'avez modifié...)

**Comment by azertyfun** [comment]
J'ai rien touche juste commenté et changé les labels pour les nouvelles normes ^^
Je vais essayer en adaptant mon propre gestionnaire de périphériques.

**Comment by L3nn0x** [comment]
Je sais pas comment t'as réussi à faire fonctionner l'écran, mais je vois pas le soucis.

**Comment by azertyfun** [comment]
En fait le DCPU après un HWQ enregistre l'ID dans les registres A et B vu que c'est un nombre de deux mots. Mais vous aviez comparé le registre B avec la première partie du mot, c'est ça qui allait pas. Du coup si ça marchait sous devkit c'est qu'il avait mal implémenté la chose.

**Comment by Yamakaky** [comment]
Justement, ce problème est résolu avec mon dernier commit ^^

**Comment by Yamakaky** [comment]
Ça marche toujours pas chez moi :sad:

**Comment by azertyfun** [comment]
Voir issue #15, le gestionnaire des périphériques ne charge que le premier hardware trouvé, il sort de la boucle trop tôt je crois.

**Comment by L3nn0x** [comment]
Je cherche l'erreur.
