### ISSUE TITLE
Erreur dans le gestionnaire des périphériques

### ISSUE THREAD

**Issue by azertyfun** [FrOSt-Foundation/FrOSt#15]
Le gestionnaire des périphériques ne détecte que le premier hardware de la liste, faudrait corriger ça xD

**Comment by L3nn0x** [comment]
C'est pas parce qu'il y a un soucis dans l'émulateur de DevCPU ?

**Comment by azertyfun** [comment]
Non, sur mon OS ça marche très bien ^^

**Comment by Yamakaky** [comment]
Ça doit être l'émulateur, parce que je voit pas pk ça détecte pas tout.

Ce détecteur est assez brouillon, il faudrait commencer à -1 et ajouter 1 au début, et utiliser push/pop au lieu du label en dur.

En parlant de gestionnaire de periph, va falloir qu'il check aussi A. Y a peu de chance qu'il y ai 2 hw avec le même B mais un A différent, mas ce jour là on aura l'air con… Et puis c'est pas respectueux de la norme.

**Comment by L3nn0x** [comment]
Je crois qu'on avait fait ça à la va vite. Faut le refaire en plus clean.

**Comment by Yamakaky** [comment]
Je m'en occupe.

**Comment by L3nn0x** [comment]
Ok.

**Comment by azertyfun** [comment]
Profites-en pour refaire tout le système, avec les init et les sauvegarde en une seule routine.

**Comment by Yamakaky** [comment]
Je galère pas mal, y a plein de trucs à faire et faut pas casser tout le système '^^'
Bref, c'est la joie. J'ai créé un branch car tout ne tiendra pas en un commit ^^. Est-ce que je remet tout à plat (je pense notamment aux noms de labels) ou j'essaye de rester un minimum compatible ?

**Comment by L3nn0x** [comment]
Il te suffit juste de refaire ce qui se trouve dans le fichier Gestionnaire_perif.

**Comment by Yamakaky** [comment]
C'est pas si simple. Par exemple, la console utilise le label `ecran_actif`. Lequel ? écran1, écran 2 ?

**Comment by azertyfun** [comment]
Hmmm bonne question c'est du ressort de Faërie :p 
Mais contente toi de refaire le détecteur de périphériques non ? Après ça sera plus simple de changer d'autres choses.

**Comment by Yamakaky** [comment]
Ok. En fait, je vas le refondre totalement, avec les defines qui vont bien.

Sur ce, je vais manger.

**Comment by L3nn0x** [comment]
ecran_actif est l'écran actif, c'est une adresse ram assignée par le sched.

**Comment by Yamakaky** [comment]
Ah ok, je viens de comprendre. Par contre, ce que je ne comprend pas, c'est pourquoi le sched le gère (oui, je sais, la perf passe d'abord). Il vaudrait mieux laisser ce label dans le driver, et écrire une routine driver pour changer d'écran actif et en informer l'écran (d'ailleurs, c'est surement de là que viennent les hwi dans le kernel ?).

**Comment by L3nn0x** [comment]
En fait, puisque chaque programme a un écran, quand on veut écrire sur un écran, il faut modifier l'endroit où on écrit. Donc dans les int (précisément), on change ecran_actif pour écrire sur le bon écran. Mais je vais simplifier tout ça, tkt.

**Comment by azertyfun** [comment]
Euh c'est normal que les routines sauvegarde_\* aie un ADD J, 1 à la fin, alors que il y en a déjà un dans la boucle ? ^^'

**Comment by L3nn0x** [comment]
Oui, parce que comme ça on évite le jsr. Mais au boot c'est pas vraiment nécessaire.

**Comment by Yamakaky** [comment]
Je m'en occupe, je vous dis ^^

**Comment by azertyfun** [comment]
Si jamais tu touches le fond regarde toujours comment j'ai fait, ça marche sur mon DevCPU ^^
https://github.com/azertyfun/SimpleOS-v2

**Comment by L3nn0x** [comment]
Dans ta fonction, tu mets J à -1 alors que tu n'en n'as pas besoin. Ça te fais faire un tour pour rien.

**Comment by Yamakaky** [comment]
non : j'ajoute 1 au début de la boucle. Comme ça j'ai pas à le faire aux multiples endroits où elle peut finir.

**Comment by azertyfun** [comment]
Le gestionnaire des périphériques fonctionne de nouveau, je ferme.

**Comment by Yamakaky** [comment]
Cool
