### ISSUE TITLE
.define TRUE FALSE

### ISSUE THREAD

**Issue by Yamakaky** [FrOSt-Foundation/FrOSt#16]
Dans ma refonte, j'ai ajouté quelques macros binaires, nottament IF_TRUE et IF_FALSE, qui sont des define de `ifn 0,` et `ife 0,`. Ça nous permettra d'ajouter un peu de sémantique au code pour les variables booléennes.

**Comment by L3nn0x** [comment]
fais gaffe, parce suivant l'ordre dans lequel on fait les comparaisons, le if prendra un mot de plus.

**Comment by Yamakaky** [comment]
Justement, c'est bon, je viens de vérifier la doc.

**Comment by L3nn0x** [comment]
ok alors.
