### ISSUE TITLE
Printf ne fonctionne plus

### ISSUE THREAD

**Issue by azertyfun** [FrOSt-Foundation/FrOSt#17]
La détection et l'initialisation des périphériques fonctionne très bien (voir 3f3f7f77a0), mais la console ne marche plus : au premier retour à la ligne, POUF, plus rien. J'ai l'impression que printf a du mal avec les retours à la ligne, je vais tenter de voir pourquoi. :(

**Comment by azertyfun** [comment]
Je dois bien avouer que je ne trouve pas d'où vient l'erreur, quelqu'un a une idée ?

**Comment by Yamakaky** [comment]
Euh, il est où ? XD

**Comment by azertyfun** [comment]
dans DriverEcran.dasm ^^

**Comment by Yamakaky** [comment]
Bon bah je vais voir ça.

C'est trop grisant ces derniers jours, on arrête pas de switcher entre 50 pages ^^ Comparé au fofo, cest plus fun !

**Comment by azertyfun** [comment]
T'as pas trouvé ? :(
Et Faërie, ptêt qu'il va trouver l'erreur à la con lui ^^

**Comment by Yamakaky** [comment]
j'ai pas vraiment cherché '^^
Je vois ça demain, promis. Voir ce soir

**Comment by azertyfun** [comment]
Bon ben j'ai comparé entre la dernière version et un commit plus ancien, y'a vraiment rien qui change si ce n'est les labels (qui sont corrects évidemment ^^). Donc le problème ne vient pas de la. Je vais chercher d'où ça vient mais je vois pas d'où du coup vu que ce n'est que au retour à la ligne que ça merde.

**Comment by azertyfun** [comment]
Okay, donc apparemment c'est pas là que ça merde, c'est juste que le printf, ainsi que le printc, refusent d'afficher des caractères plus loin que la première ligne de l'écran. Pourtant, puts fonctionne parfaitement. Étrange.
EDIT : WAIT là printf marche, je teste un truc 2 sec.
EDIT2 : Bon en fait j'ai l'impression que le printf bug juste à l'intérieur de la console. :/
EDIT3 : Finalement c'est bien le retour à la ligne qui passe pas ^^'

**Comment by L3nn0x** [comment]
Je regarde et je vous dis.

**Comment by azertyfun** [comment]
Merci parce que là je sèche ^^

**Comment by L3nn0x** [comment]
J'ai trouvé : dans p_return, il faut ajouter add I,[écran_actif] à la fin avant de quitter la fonction.

**Comment by azertyfun** [comment]
ALLELUJA merci. Quelqu'un pou commit ? Je suis sur mon portable là :p

**Comment by L3nn0x** [comment]
Moi aussi, mais dans 5 minutes je pourrais.

**Comment by azertyfun** [comment]
Du coup si la console fonctionne bien tu peux merger avec indev.

**Comment by L3nn0x** [comment]
C'est fait.

**Comment by azertyfun** [comment]
Euh chez moi je rajoute la ligne (parce que tu l'as commit dans indev et pas dans update-hw), mais ça ne marche pas pour autant. Je te ferais remarquer qu'il faut tester sur la branche hw, parce que avec ou sans ta ligne de code le printf fonctionnait bien en indev ^^'

**Comment by L3nn0x** [comment]
Ah, mince, j'avais pas vu qu'il y avait une nouvelle branche... Et t'as raison, j'avais mal lu sur mon portable, c'était bon.

**Comment by azertyfun** [comment]
Quelqu'un essaie en remplacant les defines de printf pqr les nbres originaux ? Sinon je fait ça demain ^^

**Comment by azertyfun** [comment]
ILLUMINATION ! Faut pas mettre les crochets à S[CREEN_WIDTH] ET [SCREEN_HEIGHT] !! Dire que j'ai planché une heure là-dessus xD

**Comment by L3nn0x** [comment]
C'est pas ma faute ! :angel:

**Comment by azertyfun** [comment]
Nan c'est la mienne j'ai fait un bête chercher/remplacer sans réfléchir xD
Je corrige toossa demain :)

**Comment by Yamakaky** [comment]
La branche update-hw est pas destinée à être éternelle, juste à updater le hw ^^ C'est pas une autre indev, faut pas hésiter à en créer d'autres. Regardez dans le readme, j'ai mis le lien d'un article pas mal sur la gestion des branch.

**Comment by azertyfun** [comment]
Pas con pas con. Bon demain je debug et si la console remarche je merge la branche dans indev. Je dirais même que après on pourrait merger indev avec master pisque on serait totalement compatibles avec devCPU :p

**Comment by L3nn0x** [comment]
Je peux m'occuper de corriger ces erreurs.

**Comment by azertyfun** [comment]
Bon ben ok, et dans la bonne vranche ce coup-ci :p

**Comment by Yamakaky** [comment]
L'OS est prêt pour une 0.1 ? (ou .2 plutôt je crois) Si non, on ne merge pas l'indev dans master. cf README XD

**Comment by L3nn0x** [comment]
Oui, oui...

**Comment by L3nn0x** [comment]
Voilà.

**Comment by azertyfun** [comment]
Corrigé, je ferme. Par contre, l'interruption 0x4000 ne marche pas :( (Voir issue #19)
