### ISSUE TITLE
Simplifier l'interruptHandler

### ISSUE THREAD

**Issue by azertyfun** [FrOSt-Foundation/FrOSt#18]
L'interrupt handler est vraiment compliqué et tordu je trouve, ce serait beaucoup plus simple de faire un système comme ça : 

<pre>:interruptHandler_init
IAS interruptHandler

:interruptHandler 
IFE A, 0x1
    JSR printf
IFE A, 0x2
    JSR clear
IFE A, 0x3
    JSR change_color
;Etc</pre>

**Comment by Yamakaky** [comment]
On en avais déjà discuté. J'avais proposé un système plus rapide, mais un peu moins flexible (c'est l'actuel, je crois)
http://frost-0x10c.tk/Forum/viewtopic.php?id=42

**Comment by azertyfun** [comment]
Faudrait que tu fasses une mini doc en haut de fichier pour expliquer comment ajouter des interruptions alors ça serait plus pratique :)

**Comment by Yamakaky** [comment]
Bah déjà, faudrait mettre ptr_tab dans kernel/interruptHandler ^^
Et oui, faudrait faire de la doc. Faudrait faire… Faudrait…
J'ai pas le temps aujourd'hui, je verrai ça demain.

**Comment by azertyfun** [comment]
Je m'occupe de faire la doc sur pr wiki tantôt :p

**Comment by Yamakaky** [comment]
oublie pas l'accès git ;)

**Comment by azertyfun** [comment]
L'accès git ? C-à-d ?
EDIT : ok j'ai trouvé le bouton laisse tomber.

**Comment by Yamakaky** [comment]
pour le wiki ^^
en markdown

**Comment by L3nn0x** [comment]
L'actuel est beaucoup mieux. Ton système est bien quand il y a peu d'interruptions à gérer, mais on en a trop et on cherche la rapidité.

**Comment by azertyfun** [comment]
Euké. ^^

**Comment by Yamakaky** [comment]
J'avais calculé : ton système (qui étais l'ancien de FrOSt) et plus rapide s'il y a moins de 3 int.
