### ISSUE TITLE
L'interruption 0x4000 ne fonctionne pas

### ISSUE THREAD

**Issue by azertyfun** [FrOSt-Foundation/FrOSt#19]
L'interruption 0x4000 est apparemment totalement buggée :/
Il semblerait que cette partie du scheduler soit buggée :(
Du coup la console fonctionne pas ^^

**Comment by L3nn0x** [comment]
Let me see.

**Comment by L3nn0x** [comment]
Tu peux remplacer ça par l'interruption 0x4001, elle ne passe pas par le scheduler. (En attendant que je refasse le scheduler.)

**Comment by Yamakaky** [comment]
Ça vous dit qu'on utilise les .includes ? XD

**Comment by L3nn0x** [comment]
Pour ?

**Comment by Yamakaky** [comment]
(oups, .define ^^)
Bah pour les int. Un exemple fictif : 
`.define INT_NEW_TASK int 1337`
C'st plus lisible, non ?

**Comment by L3nn0x** [comment]
Bah c'est pas trop utile vu qu'à part la console, tous les autres programmes seront sur des disquettes...

**Comment by Yamakaky** [comment]
Ouais, mais l'astuce, c'est qu'on peut inclure ce fichier dans tous les programmes tiers ! Ce serait un sorte d'API.

**Comment by L3nn0x** [comment]
Ah, pourquoi pas alors. Et on distribuerait ce fichier ?

**Comment by Yamakaky** [comment]
Bah oui, genre dans api/ par exemple.

**Comment by Yamakaky** [comment]
Du coup : 
- dans indev, on aurait toujours la dernière version
- dans master, on ferait un merge par version de l'OS, en même temps que la release (cf README, l'article sur les branches)

**Comment by azertyfun** [comment]
Très bonne idée les defines :)

**Comment by Yamakaky** [comment]
Bien sûr, ha ha !
