### ISSUE TITLE
fin des string

### ISSUE THREAD

**Issue by Yamakaky** [FrOSt-Foundation/FrOSt#2]
pour la fin des chaines de char, il faudrait prendre en compte les espaces mais aussi les \n

**Comment by boucaud** [comment]
Wut ? Que veux-tu dire par là ?
Le standard est '\0' soit 0x0

**Comment by Yamakaky** [comment]
Je parlais de \n au sens de 0x11, utilisé par le printf de Fearie

**Comment by L3nn0x** [comment]
J'avais fait un printf qui acceptait les \n et réagissait en conséquence. Faudrait que je le retrouve.
