### ISSUE TITLE
Refaire la console

### ISSUE THREAD

**Issue by L3nn0x** [FrOSt-Foundation/FrOSt#20]
Il faut refaire la console pour la rendre plus compact et plus rapide. En plus ça permettra de virer des fonctions dans les libs qui ne servent techniquement à rien...

**Comment by azertyfun** [comment]
Je veux bien m'y atteler, mais juste une question : Quand tu parle de blocs avec malloc, ce sont des mots ou des blcos de mots ? ^^'

**Comment by L3nn0x** [comment]
Gni ?

**Comment by L3nn0x** [comment]
C'est tout simple, t'as pas à te poser autant de questions : tu mets le nombre de mots que tu veux allouer dans A (la taille quoi), tu call malloc et tu utilise l'adresse qui est dans Z. Direct. Si tu veux libérer la mémoire allouée, il te suffit de donner l'adresse dans A et de call free.

**Comment by azertyfun** [comment]
Euké euké, simplement comme tu parlais de blocs à chaque fois je pensais que c'était comme pour les floppies, un nombre déterminé de mots ^^

**Comment by L3nn0x** [comment]
Non non, tkt. C'est un poil plus évolué que ça. ;)

**Comment by azertyfun** [comment]
Autre question : y'a une limite de mémoire allouée à chaque programme ? Parce que à un moment mon système fait que j'utilise 96 mots de ram (le temps de parser la commande), mais je reçois un 0xFFFF avec malloc ^^'

**Comment by Yamakaky** [comment]
Effectivement, ça pose problème ^^

**Comment by L3nn0x** [comment]
Non, mais il doit y avoir un problème. Tu n'aurais pas écris en dehors de ta mémoire allouée par hasard ?

**Comment by azertyfun** [comment]
Je verrai demain ^^

**Comment by L3nn0x** [comment]
Si tu commit je peux chercher aussi.

**Comment by azertyfun** [comment]
Bon ben la console est refaite (reste plus qu'à optimiser), je ferme.
