### ISSUE TITLE
La fonciton free n'initialise pas la mémoire ?

### ISSUE THREAD

**Issue by azertyfun** [FrOSt-Foundation/FrOSt#21]
Avec ma console (et vous pouvez tester), j'ai le problème suivant : 
J'ai tout bien corrigé le parser, très bien. Mais le problème c'est que lorsque la commande A fait x caractère et que la commande B est plus petite, alors on voit la commande B s'afficher (normal) + la fin de la commande A. Ma question est donc la suivante : La fonction free, elle met toute la mémoire allouée à zéro ou faut le faire soi-même ? ^^

**Comment by Yamakaky** [comment]
Je connais pas l'implémentation, mais normalement tu n'as pas à remettre à 0 (sauf raisons de sécurité). La zone sera soit remise à zéro à l'allocation, soit laissée telle quelle, dans le cas où le programme fait systématiquement une écriture avant une lecture.

**Comment by azertyfun** [comment]
Ben apparemment la zone n'est pas remise à zéro à l'allocation et bien laissée telle quelle. Bon ben je fais une fonction d'init alors. C'est bête quand même, mais c'est vrai que dans certains cas c'est bcp plus rapide de ne pas initialiser.

**Comment by Yamakaky** [comment]
Y a pas de malloc qui init à 0 ? Bizarre…

Si c'est pour l'écran, on init, mais si c'est pour stocker des variables, on init pas forcément ^^

**Comment by L3nn0x** [comment]
Alors, on avait décidé que ni malloc ni free ne remettrait la mémoire à 0, ça sert quasiment jamais. Par contre, j'ai implémenté une fonction qui remet à 0 une zone mémoire : efface_memoire. Cette fonction prend en argument l'adresse de la mémoire à initialiser dans A.

**Comment by azertyfun** [comment]
Trop cool merci :)
Mais en fait ça ne sert à rien pour l'instant... tu n'as pas fait de push xD

**Comment by L3nn0x** [comment]
Elle y est déjà depuis l'an pèbre, et même en int : c'est int 0x0002 avec en B l'adresse à init.

**Comment by azertyfun** [comment]
Aaah euké ^^
