### ISSUE TITLE
VFS

### ISSUE THREAD

**Issue by L3nn0x** [FrOSt-Foundation/FrOSt#22]
Il faut que quelqu'un fasse le vfs. Pour rappel, le vfs est une surcouche du fs qui permet à l'OS de se libérer des problèmes liés aux différents fs.
http://en.wikipedia.org/wiki/Virtual_file_system

**Comment by azertyfun** [comment]
Pareil, j'y connais rien je laisse à yama. Je pourrai par contre m'occuper de ls, cd et cie pour la console :)

**Comment by Yamakaky** [comment]
Je vais voir ce que je peux faire, le pb c'est que je suis en révision…

**Comment by L3nn0x** [comment]
Moi aussi. :/

**Comment by azertyfun** [comment]
Ben je peux toujours regarder, je vous tiens au courant de si j'arrive à quelque chose. Mais on ne peut pas dire que y'aie des tonnes de tutoriel sur les systèmes de fichiers :(

**Comment by L3nn0x** [comment]
Essaye d'abord de faire un fs peut-être. C'est plus facile techniquement.

**Comment by Yamakaky** [comment]
+1

**Comment by azertyfun** [comment]
Je fais le fs je fais le fs :p 
Façon il faut bien avoir un FS pour faire un VFS, c'est comme vouloir faire du piano avant d'avoir inventé la musique...

**Comment by L3nn0x** [comment]
Ou pas, vu que le vfs est juste constitué d'un sélecteur, d'une fonction pour lire et d'une fonction pour écrire...

**Comment by Yamakaky** [comment]
Bah, on peut commencer par un FS, comme ça on verra les besoins pour le VFS

**Comment by azertyfun** [comment]
Le VFS servira très certainement si on implémente notre propre système de fichier (tout comme linux supporte le NTFS mais préfère utiliser le ext).

**Comment by Yamakaky** [comment]
Genre FSF, ma spec perso, que j'implémenterai un jour ^^
