### ISSUE TITLE
[FS] Implémentation du FAT16

### ISSUE THREAD

**Issue by L3nn0x** [FrOSt-Foundation/FrOSt#23]
Il faut que quelqu'un code le(s) fs. On peut commencer soit par implémenter un fs existant, soit en inventant le notre. Aucune préférence, si ce n'est une priorité aux fs connus sur dcpu (utilisés par une majorité de personnes).

**Comment by azertyfun** [comment]
Je laisse ça à yama, je n'y connais strictement rien :/

**Comment by azertyfun** [comment]
Ah, j'ai trouvé un truc sympa quand même. Bon ben je vais commencer à coder tout ça :)

**Comment by Yamakaky** [comment]
Tu pense faire quoi ?

**Comment by azertyfun** [comment]
Un système de fichiers en FAT-16. Par contre pour une questionde performance, je n'implémenterai que les trucs capitaux (genre les fichiers n'ont pas un besoin primordial de données de date par exemple).

**Comment by Yamakaky** [comment]
Poste d'abord les specs avant de commencer à coder.

De toute façon, on a pas d'horloge ^

**Comment by azertyfun** [comment]
Ouais mais on **pourrait** en implémenter la lecture tout de même, ce que je ne ferai pas :p

**Comment by Yamakaky** [comment]
Je suis d'accord. Yamakaky, seal of approval.

**Comment by L3nn0x** [comment]
Très très bien tout ça. :D

**Comment by Yamakaky** [comment]
Du coup, quelle spec?

**Comment by azertyfun** [comment]
Voilà pour les specs (dites moi si je dois modifier quelque chose ^^) : http://azertyfun.tk/private/FAT16_FrOStSpecs.html

**Comment by Yamakaky** [comment]
Utilise plutôt [gist](https://gist.github.com/) ;)

Je vais voir à quel point tu es génial.

**Comment by azertyfun** [comment]
Ca va me faire un poil chier pour faire des tableaux ^^

**Comment by Yamakaky** [comment]
C'est vrai que c'est pas l'idéal ^^

Petite remarque pour commencer : tu devrait plutôt utiliser des mots de 16 bits, et non des bytes (à moi que tu ne comptes des bytes de 16 bits ?)

**Comment by L3nn0x** [comment]
Et fais gaffe, il faut essayer de tenir compte des limitations du hw, qui sont une lecture par blocs de je-sais-plus-combien.

**Comment by Yamakaky** [comment]
Il en a tenu compte, ce FS gère des blocs de 512 mots.
- J'ai l'impression que ton FS ne gère pas les sous-dossiers ?
- J'ai pas compris comment fonctionne la table d'allocation.
- Pour la duplication de sauvegarde du premier secteur, on peut s'en passer, les floppies sont virtuels XD
- Pourquoi pas un nom de disque plus long ? 11 char me semble un peu court
- Même remarque pour les noms de fichier. Et pourquoi s'embeter avec l'extension séparée du nom de fichier ? Autant faire à la Unix où l'extension importe peu voir peut être absente.

**Comment by L3nn0x** [comment]
Ok. J'aime tes idées Yama, même si dans un premier temps les sous-dossiers ne sont pas les plus importants.

**Comment by azertyfun** [comment]
- Si, si tu met le premier byte du nom de fichier à 0x05 et le second au numéro du cluster parent.
- En gros dedans t'as un certain nombre d'entrées (dont tu peux voir la forme dans mon tableau de la mort qui tue). La première entrée correspond au premier fichier enregistré dans la zone d'enregistrement des fichiers. La seconde entrée au second fichier, etc...
- Oui, mais dans le jeu les floppies pourront être altérés par les radiations. Donc autant prévoire une implémentation future de la gestion de plusieurs FATs (en attendant seul le premier sera lu).
- Je ne saurais pas faire de noms de fichiers plus long pour la simple et bonne raison que cela casserait totalement la compatibilité avec d'autres systèmes utilisant le FAT16, ce qui est quand même la raison pour laquelle on développe ce FS. On développera sans doute après un autre système de fichier, propre à FrOSt, pour pouvoir lire et écrire à la fois sur le FAT16 et un système avec des noms de fichiers aussi longs que tu veux :p 
- Ben même remarque que pour les noms de fichiers, on ne sait pas changer l'implémentation. Ensuite, faire l'extension séparée ça permet techniquement d'économiser à la fois de la place sur le disque (vu que le "." est implicite) et d'éviter de devoir parser les noms de fichiers.

J'espère avoir répondu à tes questions :p

**Comment by Yamakaky** [comment]
- Ok, j'ai vu ça après ^^
- Ah d'accord. Du coup, les fichiers sont listés 2 fois : dans le dossier et dans la table ?
- Pas faux ^^
- Ok. Ça s'appelle un VFS ^^

**Comment by azertyfun** [comment]
- Pas grave, même moi je me suis posé la question quand tu as dis ça :p 
- Non, ils sont listés uniquement dans la FAT. Le dossier ne sert que de point de référence, c'est un fichier vide qui peut -être considéré comme un parent par des sous-fichiers.
- -
- Ca s'appelle FSF et le VSF s'occupera de tronquer les noms de dossier si on tente d'écrire sur du FAT16 et de les mettre on complet si on écrit sur  du FSF :p

**Comment by Yamakaky** [comment]
… Du coup, comment on fait pour retrouver un faitchier à partir de son chemin ?

**Comment by azertyfun** [comment]
Tu récup le nom de fichier en parsant et tu compares son arborescence à celle des fichiers qui ont le même nom que lui :p

Par contre se pose la question de la défragmentation, je suppose que le mieux est d'intégrer defrag.exe à la racine. Enfin, je fait le VF et le VFS avant :p

**Comment by azertyfun** [comment]
Ah oui, au fait, j'utilise bien des bytes de 8 bits, pas trop le choix c'est la norme officielle. Ca va me faire chier mais pas le choix :/

**Comment by Yamakaky** [comment]
Oui, mais tu utilise la table ou pas ?

Bah non, une simple fonction dans le driver ^^. De toute façon, tous drivers confondus, le plus simple est de cloner le disque sur un autre. Comme ça le driver remet tout bien. Et puis on s'en fout un peu de la défragmentation, l'accès est à temps constant XD

Dommage…

**Comment by azertyfun** [comment]
Rhâ tu me fait douter je vais voir x)

Pour la défrag, le truc c'est que c'est une fonction "optionnelle", elle ne sert pas à l'utilisateur lambda qui n'utilise pas de disque, et une fonction driver prendrait autant de place que le fs en lui-même ^^

**Comment by azertyfun** [comment]
Ok je me sujs emmêlé les pinceaux avec la FAT, regarde plutôt ça avant que je màj les specs : http://www.tavi.co.uk/phobos/fat.html#file_allocation_table
EDIT : Ok c'est bon j'ai updaté mes specs avec un petit schéma en plus :p

**Comment by Yamakaky** [comment]
Alors c'est pas la peine d'en écrire une, suffit de clone le disque. ^^

**Comment by azertyfun** [comment]
Ben je doute que quiconque aie envie de payer des disques à tour de bras pour faire une défragmentation ^^

**Comment by Yamakaky** [comment]
Pas besoin d'une masse, juste un en plus ^^

**Comment by azertyfun** [comment]
Même, on a aucune idée du prix d'un disque in-game. Et franchement ça fait pas pro un OS pour qui la seule solution de défragmentation est de tout copier sur un nouveau disque xD
M'bref façon ça c'est la dernière étape, avant y'a du chemin à parcourir ! ^^

**Comment by Yamakaky** [comment]
Bah c'est la méthode recommandée par Apple, vu que les FS unix se fragmentent très peu ^^

**Comment by azertyfun** [comment]
La méthode apple c'est vraiment un exemple ? Bref.
Ensuite là on te parle de FS Windows. Et pas un récent en plus. Donc, si, la défragmentation est nécessaire. Ce qui me fait penser que je devrais le faire sur mon PC. Et **sans** jeter mon disque dur :D

**Comment by azertyfun** [comment]
Bullshit, je fais compter des bytes de 16 bits, je doute qu'un quelconque OS s'amuse à implémenter des bytes de 8 bits. Na.

**Comment by Yamakaky** [comment]
That was a :trollface:

**Comment by azertyfun** [comment]
On n'est jamais sûr de ce genre de chose avec apple :trollface:

**Comment by L3nn0x** [comment]
Sinon, une solution est de copier tout le disque en ram (ou au moins une partie) et défragmenter "par morceaux".

**Comment by azertyfun** [comment]
Ben oui xD

**Comment by Vaasref** [comment]
Missclick

**Comment by azertyfun** [comment]
Bon, j'ai pris un peu d'assurance avec la gestion des disques sur le DCPU. Du coup je suis en train de bosser sur le FS, et ça s'annonce très bien. Il me reste un ou deux bugs à corriger et je serai en mesure de détecter et afficher des infos sur un disque compatible avec FFAT-16 (puisque on ne sait pas comment le FAT-16 sera implémenté, j'ai préféré faire une variante que l'on pourra facilement adapter par la suite).

**Comment by azertyfun** [comment]
J'Y CROIS PAS !
Depuis deux heures que je debug je me suis trompé de registre pour le malloc T_T

**Comment by Yamakaky** [comment]
XD

L'utilisation de macros permettrait d'éviter ces problèmes. Mais bon, DevCPU a l'air un peu en veille...

**Comment by azertyfun** [comment]
De toute façon il faut que je puisse gérer les erreurs moi-même, parce que dans ce cas je dois passer par un bout de code qui libère la mémoire, POP les registres et retourne un code d'erreur perso. Cay pas une macro qui va faire ça xD

Mais sinon au final le malloc c'est en B ou en A ? Memoire.dasm raconte en A, mais l'interrupt handler en B ._.
EDIT : Euké j'avais pas capté que B dans l'IH = A dans la fonction. My fault.

**Comment by azertyfun** [comment]
2c81abb J'ai ENFIN terminé l'implémentation des bases de F-FAT16. Il est maintenant possible de formater un disque valide, de lire les infos dessus et de détecter sa validité. Demain j'optimise ça et j'ajoute la gestion des fichiers (j'ai fait un petit plan et tout).

Sinon pour la routine d'initialisation (appelée uniquement au démarrage théoriquement), il faut des push regs ou pas ?

**Comment by Yamakaky** [comment]
Cool !

Faut voir, ça dépend de l'implémentation de la séquence de boot. Si c'est une suite de jsr, y a pas de problème ;)

**Comment by azertyfun** [comment]
Mhmm, pour utiliser malloc faut être dans un programme. Donc soit on indentifie le système comme un programme, soit on doit faire jsr init_disk au début du programme launché (ce que n'est pas plus bête du fait qu'un programme qui n'en a pas besoin ne le fera pas).
Par contre pour l'instant les infos sur le disque sont accessibles depuis un label, il va falloir que je change ça. ^^'

**Comment by Vaasref** [comment]
Les meeeecs c'est pas sympa de toucher a FrOSt quand on est en piscine.

Du coup je prends du retard sur FrOSt la.
(et faites pas chier sur les accents avec des clavier qwerty c'est la mort a faire)

**Comment by Yamakaky** [comment]
Quand TU es en piscine ^^

**Comment by Vaasref** [comment]
Et @FaerieFrOSt il compte pas ?

**Comment by L3nn0x** [comment]
Bijour, je suis en piscine, mais c'est pas grave, c'est cool que vous continuiez a avancer dessus.
Azertyfun, je rajouterai ensuite des int pour l'acces au VFS. Faut maintenant un VFS qui puisse ajouter une couche d'abstraction sur le FS. Je vous fait confiance pour ca. :)

**Comment by azertyfun** [comment]
Houlà. D'abord faut arriver à faire le FS hein. Parce ce que je suis en train de coder la fonction newFile, et rien que ça c'est la mort.
Le problème de ce genre de coding c'est que tu es obligé de chier 200 lignes avant de pouvoir tester le code, donc généralement il y a plusieurs bugs qui s’entremêlent. Je dois avoir un ratio de 15-20% de coding et 75-80% de debug... ._.

**Comment by L3nn0x** [comment]
XD, ça me rappelle quand je tentais de coder mon foutu ext_2 pour mon OS... Bonne chance en tout cas.

**Comment by Vaasref** [comment]
Mais aussi pourquoi tu code des bugs aussi... C'est tellement 2012 !

**Comment by Yamakaky** [comment]
c'est chiant, y a pas de bouton +1 ou j'aime XD

**Comment by azertyfun** [comment]
Tant qu'on est dans le déterrage de code, j'ai repris le dev du FFAT-16 (need MOAR CODING) et je crois que vu que j'ai perdu l'intégralité des specs je vais refaire ça en bien plus simplifié et rapide. En gros une seule FAT et nombre limité de fichiers (?). Et les specs sur gist.
EDIT : Voilà le gist ! https://gist.github.com/azertyfun/7899244

**Comment by L3nn0x** [comment]
J'ai besoin que tu m'aide pour les FS mec. Je galère à mort avec mon foutu ext2...

**Comment by Yamakaky** [comment]
ext2 ? t'es pas un peu ambitieux pour le matos disponible ?

**Comment by L3nn0x** [comment]
Je parlais de mon OS sur x86 :p

**Comment by Yamakaky** [comment]
Ah ^^ Ca avance ?

**Comment by azertyfun** [comment]
Waah j'y connais rien en FS, mon machin y'a deux mots dans le header et 2 mots en début de fichier... Alors de l'ext2 x)

**Comment by L3nn0x** [comment]
Dommage ^^
J'aimerai bien avancer, mais comme j'arrive pas à écrire sur ce foutu ext2, en attendant je fais quelques fonctions de base, style des fonctions de la libc, des fonctions sur les chaînes de caractères et des fonctions assez utiles que je rajouterai dans mon OS. ;) Pour l'instant, j'ai environs une centaine de fonctions, mais je compte bien en ajouter.

**Comment by azertyfun** [comment]
Ca m'intéresserait bien d'avoir ton OS tout de même, je suis curieux :D

**Comment by L3nn0x** [comment]
:)
Je vais essayer de le mettre sur github.

**Comment by azertyfun** [comment]
:D Merci o/

**Comment by L3nn0x** [comment]
Tada !
https://github.com/FaerieFrOSt/Creeks

Hésite pas à proposer des modifs, j'ai pas encore totalement factorisé le code par exemple... J'ai aussi plein de nouvelles fonction dans la lib C, un ls un peu mieux, un projet d'implémenter tcc dans mon OS pour avoir un compilateur, etc...

**Comment by Yamakaky** [comment]
cool ! on peut le lancer ? (avec qemu d'après ce que je vois)

**Comment by L3nn0x** [comment]
Bah oui, sinon je l'aurai même pas mentionné... Normalement, vu que je viens de rajouter hd.img, vous pouvez juste faire un qemu -hda hd.img

**Comment by azertyfun** [comment]
J'installe xubuntu sur un vieux portable (sous windows et fier de l'être), et je regarde tout ça o/
Encore merci ! Ca m'intéresse vraiment, je suis assez curieux de voir comment fonctionne un kernel en C :D

**Comment by L3nn0x** [comment]
Fais-toi plaiz, surtout si tu veux proposer des trucs ;)
Je suis ouvert à tout système de fichiers si on m'en code un. :p
