### ISSUE TITLE
[FS] Implémentation du FSF (FrOSt Smart Filesystem)

### ISSUE THREAD

**Issue by Yamakaky** [FrOSt-Foundation/FrOSt#24]
WIP ;)

**Comment by L3nn0x** [comment]
Un jour faudra que je demande ce que ça veut dire WIP et LMAO (ou un truc du style)...

**Comment by Yamakaky** [comment]
Euh, le web est ton ami !
Work In progress.

**Comment by L3nn0x** [comment]
Hum, j'aime pas le web. Je préfère google. XD

**Comment by Yamakaky** [comment]
J'ai mis en ligne un premier jet des specs de FSF. Qu'en pensez-vous ?
https://github.com/FrOSt-Foundation/FrOSt/commit/6e1df18cee866780eab851a930b354e637b86e80

**Comment by Vaasref** [comment]
Alors perso ya un truc que j'ai en horreur c'est le dossier racine. Arrêtez avec ça !

C'est pas pratique, les lettres par lecteur c'est bien plus lisible, rapide à taper, simple quoi.

**Comment by Yamakaky** [comment]
C'est ton avis.

EDIT : tu parles bien du VFS ?

**Comment by Vaasref** [comment]
J'ai dit "perso" au début de mon message, pas besoin d'en faire un pour me dire que je parle pour moi même...

@EDIT : Sinon, oui, plutôt de la façon dont l'utilisateur vois l'adresse.

**Comment by Yamakaky** [comment]
Si tu veux que je réécrive ton message en inversant le sens je peux le faire, mais ce sera pas vraiment plus constructif.

Concernant la raison pour laquelle je préfère le VFS à la windows-attitude, c'est la modularité. Sous windows (et macOS d'une certaine manière), les fichiers sont plus ou moins regroupés dans un dossier par programme (en gros). Sous Unix, les fichiers sont regroupés par type. On a /usr qui contient les données statiques (binaires, images…), /var pour les données variables (saves de jeux…), /etc pour la config système et j'en passe. Du coup, tu peux adapter ta config physique pour en tirer partie, avec par exemple /var sur HDD et /usr sur SSD (pas d'écritures donc peu d'usure). Mais tu peux aussi tout mettre sur la même partition. L'utilisateur s'en fiche au final puisque c'est transparent grâce au VFS.

Après relecture, c'est peut-être pas ce dont tu veux parler ?

**Comment by L3nn0x** [comment]
Faites attention à la distinction fs/vfs. J'ai l'impression que vous confondez les deux. Le fs (file system) est par exemple le FSF de Yama ou le FAT16 de Azertyfun. Le vfs est un niveau d'abstraction qui vient unifier les différents fs pour rendre transparent le fait de changer d'organisation sur le disque. En gros, le vfs peut être considéré comme un gros switch alors que le fs est vraiment une organisation à part entière.
