### ISSUE TITLE
[console] Commande color

### ISSUE THREAD

**Issue by Yamakaky** [FrOSt-Foundation/FrOSt#25]
Il est possible de lancer une commande du style `color 0x1234` qui met la couleur, mais aussi modifie le texte tappé…

**Comment by L3nn0x** [comment]
Normal, vu qu'on fait un bor [color], je vais corriger ça.

**Comment by L3nn0x** [comment]
Voilà corrigé.

**Comment by Yamakaky** [comment]
cool
