### ISSUE TITLE
[console] Char non ascii

### ISSUE THREAD

**Issue by Yamakaky** [FrOSt-Foundation/FrOSt#26]
Il faudrait ne pas afficher les char non ascii tapés dans la console (par exemple les touches fléchées, ctrl ou maj).

**Comment by L3nn0x** [comment]
Elle ne sont pas affichées de base me semble-t-il.

**Comment by Yamakaky** [comment]
Je te confirme que si ^^

**Comment by L3nn0x** [comment]
Je vais corriger ça.

**Comment by L3nn0x** [comment]
C'est bon, c'est corrigé. Bien vu Yama. :)

**Comment by Yamakaky** [comment]
Cool !

**Comment by Yamakaky** [comment]
Bon en fait, j'étais sur `indev`. L'important, c'est que ce soit corrigé, non ?

**Comment by L3nn0x** [comment]
J'ai corrigé sur indev aussi. ;)

**Comment by Yamakaky** [comment]
Euh, évite. Du coup, on se retrouve avec deux commits différents qui font la même chose. Ça aurait été corrigé au merge de consoleAmélio. Courage, tu finira par maîtriser git et martyriser les nouveaux arrivants XD

**Comment by L3nn0x** [comment]
Non, j'ai pas corrigé sur consoleAmelio. ^^"
