### ISSUE TITLE
[console] Commande pour éteindre l'ordi

### ISSUE THREAD

**Issue by Yamakaky** [FrOSt-Foundation/FrOSt#27]
Genre `exit` par exemple.

**Comment by L3nn0x** [comment]
Ça sert à rien...........

**Comment by L3nn0x** [comment]
Voilà, c'est implémenté avec shutdown, mais ça sert à rien...

**Comment by Yamakaky** [comment]
Ça sert à rien, mais autant mettre la commande non implemented dès maintenant ^^

**Comment by L3nn0x** [comment]
Oui, mais en même temps, je vois pas trop pourquoi on implémenterai un truc qui sert à rien. De toute façon elle est là, fonctionnelle.

**Comment by Yamakaky** [comment]
Pour l'instant elle sert à rien parce qu'on ne peut pas éteindre le DCPU. Dans le futur, ce sera très probablement possible.
