### ISSUE TITLE
[memoire] fonctionnement de malloc

### ISSUE THREAD

**Issue by Yamakaky** [FrOSt-Foundation/FrOSt#28]
Dans [memoire.dasm](https://github.com/FrOSt-Foundation/FrOSt/blob/indev/kernel/Memoire.dasm#L11), c'est marqué 'A contient la taille, retour de l'adresse dans Z si B=0xFFFF alors erreur'. Du coup, quel registre contient le code d'erreur ? Si c'est B, pourquoi ???

**Comment by L3nn0x** [comment]
malloc demande la taille en A, et renvoie un pointeur en Z. Si le pointeur vaut 0xFFFF, alors l'allocation n'a pas fonctionné. Ya pas de B qui entre en jeu...

**Comment by Yamakaky** [comment]
C'est bien ça. Pourtant, dans la doc :
'retour de l'adresse dans Z si B=0xFFFF alors erreur'
Je dis ça parce que j'ai commencer à [mettre des defines partout](https://github.com/FrOSt-Foundation/FrOSt/commit/81a0a6751b652f91a71b27a3222c689209193b55).

**Comment by L3nn0x** [comment]
Hum, c'est une ancienne doc ça, non ? Sinon c'est une erreur...

**Comment by Yamakaky** [comment]
Bah, pas grave, je corrige.
