### ISSUE TITLE
Puts ne fonctionne pas.

### ISSUE THREAD

**Issue by L3nn0x** [FrOSt-Foundation/FrOSt#29]
Puts ne fonctionne pas. En fait, il ne s'arrête jamais. Mais c'est pas compliqué à résoudre, il ne détecte pas le '\0'.

**Comment by Yamakaky** [comment]
Tu veux dire qu'il ne prend pas en compte \0 ?

**Comment by L3nn0x** [comment]
Yep, that's it. J'ai juste trop la flemme de stash mes modifs sur le sheduler pour pousser une maj d'une ligne...

**Comment by Yamakaky** [comment]
Alors fallais dire dans ton post que ce bug serait résolu dans pas longtemps ^^

**Comment by L3nn0x** [comment]
T'es jamais content... :p

**Comment by Yamakaky** [comment]
Moi aussi je t'aime… XD

**Comment by L3nn0x** [comment]
XD

**Comment by Vaasref** [comment]
Il a l'air de plutôt bien marcher maintenant, issue à fermer ?

**Comment by L3nn0x** [comment]
Je vais lire ton code et je te dirais. :)

**Comment by azertyfun** [comment]
Si le coup des push/pops inversés est réparé oui pas de PB (désolé pour cette faute grossière ^^')
