### ISSUE TITLE
Un logo IG pour FrOSt ?

### ISSUE THREAD

**Issue by Vaasref** [FrOSt-Foundation/FrOSt#31]
Je propose ça je me suis pété le tronc pour le faire mais je l'ai fait.

http://puu.sh/2VJVD.png

Alors c'est un pixelisation comme j'ai pu d'un panorama du Mont Blanc, après c'est un peut adapté pour lui donner un peu de gueule.

Ça ma permit de passer un petit coup de plumeau sur le driver du LEM, parce que franchement entre les noms de fonctions en français et anglais, les noms trop généraux, les push-pop dans le mauvais sens et la syntaxe totalement chaotique, bah ça en avait bien besoin.
Je pusherai aujourd'hui ma branche.

Z'en pensez quoi ?

**Comment by azertyfun** [comment]
Très sympa, un écran de démarrage comme ça ça donnerait de la gueule à l'OS :)

**Comment by Yamakaky** [comment]
Euh, t'as vérifié que c'est affichable ?

**Comment by azertyfun** [comment]
Y'a pas de raisons puisque on peut faire du pixel par pixel avec le DCPU.

**Comment by Yamakaky** [comment]
Pas exactement, on reste limité à 2 couleurs par 8*4 pixels (1 char).

**Comment by azertyfun** [comment]
Je crois qu'il y a un flag non officiel pour afficher des pixels ^^'

**Comment by Vaasref** [comment]
Les mec arretez vos chars, je l'ai déjà codé.

D'ailleurs, c'est un screen du LEM.

**Comment by Yamakaky** [comment]
Je pouvais pas savoir ^^'
Cool alors

**Comment by Vaasref** [comment]
Non tu pouvais pas savoir, dire que je l'avais fait pas imaginé hein, montrer un screenshot qui ressemble quand même bien à un LEMet dire "Ça ma permit de passer un petit coup de plumeau sur le driver du LEM"
C'est pas du tout suffisant pour comprendre.

**Comment by L3nn0x** [comment]
Des push/pop pas dans le bon sens ? Je suis curieux de savoir où...

Sinon, c'est pas mal. :)

**Comment by Vaasref** [comment]
Regarde driverEcran.dasm à la fin le puts

https://github.com/FrOSt-Foundation/FrOSt/blob/indev/Hardware/Ecran/DriverEcran.dasm#L282

**Comment by L3nn0x** [comment]
Ah oui, cette fonction. Elle plante. ^^"
J'avais laissé la correction à Azertyfun, mais on dirait qu'il a disparu. De toute façon, elle sert à rien pour l'instant cette fonction, vu qu'on a le printf.
