### ISSUE TITLE
Convention de nommage.

### ISSUE THREAD

**Issue by Vaasref** [FrOSt-Foundation/FrOSt#33]
C'est n'importe quoi les labels ya des nom en français d'autres en anglais, et encore d'autre en  mix anglais français, et d'autres qui sont trop générique et qui pourraient être en double.

Il faudrait que ce soit un peu plus clair.

Je propose donc : 

```
:<nom périf / nom fichier (pas forcément en entier) / nom programme>_<nom de fonction>_<variante de la fonction>
```

Pour le premier <> c'est bien sur soit l'un soit l'autre, mais il faut que ce soit unique au fichier.
Pour le nom de la fonction je parle bien d'un nom de type "setBuffer" toujours commencer par des minuscules et une majuscule à chaque mot normalement découpé.

Alors ça ne toucherait pas tellement tout ce qui est kernel, puisque vous semblez vouloir utiliser les noms déjà existant.

**Comment by Yamakaky** [comment]
Je suis d'accord. J’essaierai de l'appliquer à fsf ^^

**Comment by L3nn0x** [comment]
Tu le fais ? Cool ! :D (Je parle de fsf. :p )

**Comment by Yamakaky** [comment]
Oui ^^
Je prend le train 2\* cette semaine (au fait, je serait pas trop joignable d'ici samedi)

**Comment by azertyfun** [comment]
J'ai toujours codé comme ça, et je précise même que les noms de fonctions ne doivent pas contenir d'underscores, et que les loops doivent de préférence avoir un nom clair autre que loop (même si ça dérange pas si y'en a qu'une et que son utilité est claire). On peut donc faire :programmeDeLaMort_routineMegaUtile_nomDeLaLoop. Et par pitié faites vos nom de routine en Anglais et commentez les en Français si vous voulez parce que le français n'est pas du tout adapté pour faire des noms de variables ou de fonction ^^'

**Comment by Vaasref** [comment]
Pour l'intérieur des fonction moi je reprends le label de la fonction puis si je reviens en arrière je met un "_loop0" et si je vais vers l'avant je "_skip0" après j'incrémente.

Du coup c'est toujours unique.

Et je commence à 0 hein pas à 1 on est programmeur pas lambda

**Comment by azertyfun** [comment]
Autant que possible il faut éviter le "skip", c'est pas forcément très clair (moins naturel à lire). Mieux vaut ça : 

<pre>:func_loop0
add A, 1
IFN, A, 50
    set PC, func_loop0</pre>

que

<pre>:func_loop0
ife A, 50
    set PC, skip0
add A, 1
set PC, func_loop0</pre>

**Comment by Vaasref** [comment]
Non mais regarde comment je les utilisent déjà, quand je skip, je skip. Je break pas.
