### ISSUE TITLE
checksum kernel ou lib

### ISSUE THREAD

**Issue by Vaasref** [FrOSt-Foundation/FrOSt#34]
Du coup on choisis quoi ?

Ca a pas eu l'air de trop déranger @FaerieFrOSt quand il l'a modif. Et moi franchement je le classe dans les truc de base mais dans le genre totalement.

**Comment by L3nn0x** [comment]
ça m'a pas dérangé parce que j'était plus très frais à ce moment, mais je propose de le mettre dans lib. Parce qu'après tout, quelqu'un peut très bien décider de ne pas l'ajouter à l'OS.

**Comment by Vaasref** [comment]
C'et dingue comme ça me parait vital dans un milieu oui l'on ne peux pas être sur que des données ne sont pas corrompues.

**Comment by L3nn0x** [comment]
Oui, mais en même temps, si un programme nécessite quasiment toute la mémoire, il faut avoir le choix quand au chargement des libs. Dans ce cas là, il n'y aura pas de soucis pour les radiations, vu que toute la mémoire sera corrompue quoi qu'il se passe...

**Comment by Vaasref** [comment]
Prendre des exemples à l’extrême n'est pas la bonne chose à faire. Il ne faut pas oublier le gameplay. Si un pulsar sera très certainement efficace dans la corruption intégrale des données, une utilisation normale n’entraînera jamais la corruption d'une grande partie tout du moins d'une partie significative d'un seul coup.

**Comment by azertyfun** [comment]
De façon logique, aucun mot ne sera modifié tant qu'on ne sera pas dans une zone "à risque". Je ne crois pas que notch est du genre à implémenter ce genre de pourcentage aléatoire, ce serait trop gênant pouyr 80% des OS.

**Comment by Vaasref** [comment]
Les rayons cosmique c'est partout, tout le temps. Une zone à risque c'est justement à éviter sinon toi aussi tu grille.

**Comment by L3nn0x** [comment]
Non, il avait précisé que ce ne serait pas partout. Enfin, c'est comme ça que je l'avais compris...

**Comment by Vaasref** [comment]
J'ai pas vu ça, mais bon, je te fais confiance.

Après effectivement entre les étoiles c'est plutôt vide, ça devrait être plutot calme, mais ce sera aussi plutôt inintéressant. Ce qui est intéressant ce sont les planètes et les champs d’astéroïdes et ça c'est quand même plutôt dans les sphères d'influences des étoiles que l'on en trouve.

**Comment by L3nn0x** [comment]
Enfin, on a bien une ceinture d'astéroïdes aux alentours de Pluton quand même...

Je pensais à un logiciel de cartographie des planètes/étoiles couplé à un détecteur longue portée.

**Comment by Yamakaky** [comment]
Re !

Ça n'a pas beaucoup d'importance. Je l'ai déplacé dans lib/ car ce n'est pas à mon sens une fonction à mettre dans kernel/. Ce dossier est à mon avis réservé à la gestion de la mem, des int, le scheduler et je dois en oublier.
