### ISSUE TITLE
Propriétaire ou déjà libre ?

### ISSUE THREAD

**Issue by Vaasref** [FrOSt-Foundation/FrOSt#35]
Par rapport à la création du libre 0x10c se situe tout de même dans les premières années, et donc, je me suis posé la question vis à vis du RP : 

FrOSt est-il libre IG ?

Qu'il le soit pour nous c'est pas le problème, mais pour les utilisateurs d'0x10c c'est pas dit, quel agence spatiale équiperait dans ses vaisseau des technologie issues du libre ? Maintenant je veux bien mais dans le contexte d'0x10c, j'imagine qu'il n'y avait que des firmes industrielles propriétaires qui inspirait confiance à ceux envoyait des choses dans l'espace.

Du coup je me demandais si je pouvait m'occuper du côté RP, ce qui donnera à FrOSt un cachet indéniable.

Allez soyez sympa, dites non à la première question et laissez moi faire le RP :D

**Comment by Vaasref** [comment]
J'ai vraiment trop envie de mettre (éventuellement optionnel hein) au lieu des messages disant que c'est pas implémenter par exemple des messages disant que c'est disponible dans une upgrade payant. Ou de mettre des écrans de plantages te disant d'aller voir un technicien. Non vraiment ce serait trop marrant.

Alors oui avec des macro pour ne pas compiler le fun ce serait mieux, mais bon pour ce qu'on prend de RAM c'est pas ouf grave quoi.

**Comment by Yamakaky** [comment]
Si je comprend bien, tu voudrais que FrOSt reste libre IRL, mais que IG il soit développé par une puissante compagnie, la FrOSt Coorporation Unlimited © ? … Ouais !

Pour les non implemented, ce serait cool. Par contre, vu qu'on a les macros et IFDEF, t'a qu'à mettre une variable qui définit à la compilation si le 'rp' doit être compilé. Et je veux un écran bleu.

**Comment by Vaasref** [comment]
J'avais aussi pour projet de le mettre hein.

**Comment by Yamakaky** [comment]
Franchement, ça pourrait être simpa, tant qu'il reste libre irl.

**Comment by Vaasref** [comment]
Jamais eu l'intention de changer ça, mettre des backdoors oui, mais pas qu'il soit plus libre.

**Comment by L3nn0x** [comment]
Par contre, si tu pouvais faire une branche à part pour ça, je pense que ça pourrait être bien. :) Non pas que je sois contre, mais j'aimerai pouvoir dire : voilà l'OS le plus rapide et le plus compact et il est français. :)

**Comment by Vaasref** [comment]
Ça sert à quoi de faire un OS  pour qu'il soit le plus rapide, un OS ne rivalise pas en rapidité avec un program loader plus léger.

**Comment by L3nn0x** [comment]
C'est pas faux, mais j'aimerai pouvoir proposer notre OS pour des systèmes critiques. Après, le choix sera bien sur fait par les clients, mais bon.

On peut toujours proposer plusieurs version de notre OS hein. C'est juste trois modifications qu'on ajoute/retire après tout.

**Comment by azertyfun** [comment]
+1. Le mieux serait d'avoir une branche indev-official pour la version jouable IG :)

**Comment by Yamakaky** [comment]
? Bah non, la version jouable IG est master ^^

**Comment by azertyfun** [comment]
Ouais mais un master rapide et un master jouable alors ça serait pas mal. o/

**Comment by Vaasref** [comment]
Ya qu'un master.

De toute façon si c'est avec un ifdef, puisque de toute façon on est obliger de pull si on veux avoir du compiler celui qui compile peux bien choisir sa version dans un fichier prévu à cet effet.
