### ISSUE TITLE
Touche de Rescue System

### ISSUE THREAD

**Issue by Vaasref** [FrOSt-Foundation/FrOSt#37]
Alors en pensant au conséquences d'un plantage maison je me suis dit que on a deux possibilité en cas de plantage et d'écriture sauvage sur la RAM : 
- incrémentation jusqu'à effacement du prog qui écrit
- décrémentation jusqu'à effacement du prog qui écrit

De cette base de réflexion je me suis dit que dans l'un des deux cas le second on avait certainement le temps de voir venir, certes peu, mais au cas où il serait selon moi très intéressant de mettre un microprogramme de remplissage de RAM par disquette.

Je vous fais le petit scénario:
1. Je lance un programme merdé
2. Oh putain de bordel de merde, mon affichage fout le camp
3. En un éclair j'éteint le DCPU afin d'épargner le maximum de RAM
4. Ayant un OS ou au moins un futé (:[}) travail dessus, j'insère la disquette de sauvegarde système puis relance mon DCPU en appuyant sur une touche bien spécial
5. Fort heureusement le début de la RAM n'a pas été touchée, se lance alors grâce à l'appuis du bouton le microprogramme de restauration du système.
6. Le microprogramme définit [0xFFFF] à 0 dès que ce mot passera a 0xFFFF toute la RAM aura été remplacée par la copie issue de la disquette. Même le microprogramme se sera auto-restauré si il lui manquait la fin puisqu'il a lancer l'algorithme de restauration des premier 512 mots de la RAM en une somme de mot minimale afin de résister a un effacement partiel.

Donc il faut avant même de booter placer le microprog, il va poller tout seul comme un grand le clavier, si la touche est pressée alors PAF il se lance et là c'est la boucherie de bug.

Alors fonction à rajouter ?

Sinon on peut aussi au lieu de prendre de la place pour faire la détection de clavier, faire un microprog qui lance systématiquement la restauration, ce qui implique qu'il faut avoir une copie de l'OS à chaque lancement. Plus contraignant mais diablement plus efficace.

**Comment by Vaasref** [comment]
> Comment ça je procrastine pour pas faire le driver M35FD ?

**Comment by L3nn0x** [comment]
Dommage, la ram s'efface dès que le dcpu est éteint...

**Comment by Vaasref** [comment]
Euh, il a pas un mode lancé et non lancé plutôt ? sinon c'est proprement impossible d'écrire dessus hein.

**Comment by L3nn0x** [comment]
Bah non, pour l'instant on sait même pas comment le boot se fera...

**Comment by Vaasref** [comment]
De toute façon il est impossible de lancer un programme sur RAM si on ne peux pas stopper le DCPU pendant que l'on écrit dessus.

Ou si la RAM se vide effectivement a la mise hors tension.

**Comment by Yamakaky** [comment]
Bah déjà de base c'est de la RAM, donc elle s'efface à l'extinction. Et ton système me parait un peu foireux, t'es au courant que le DCPU fait 100 000 ticks par seconde ? ^^

**Comment by Vaasref** [comment]
C'est de la RAM certes, mais de toute façon il y aura un mode ou le DCPU ne tournera pas, alimenter ou non je ne sais pas, mais il est nécessaire d'avoir un mode de fonctionnement permettant d'écrire la RAM. Et donc vu comment ce serait absolument pas pratique sinon, il y aura probablement aussi un moyen pour de faire entrer le dcpu dans ce état.

En quoi il est foireux si le DCPU va à 100 000 tps ? Inefficace théoriquement peut-être mais bon.

Une boucle qui écrase tout ça prends facilement 4 ticks non ?

**Comment by Yamakaky** [comment]
Y aura probablement un truc type bios.
Faudrait que ça efface immédiatement la zone d'affichage, sinon il peut se passer un moment avant que ça soit repéré.

**Comment by Vaasref** [comment]
Vous avez déjà travaillé sur microcontrôleur ? J'ai pas l'impression.

Et si ça écrase tout ca écrase forcément les buffer des affichages.

**Comment by Yamakaky** [comment]
Non
Ouais, mais si ça écrase tout y a rien à récupérer ^^

**Comment by Vaasref** [comment]
Non, si ça écrase tout c'est que forcément ça passera pas le buffer un jour où l'autre donc, oui ce sera visible j'ai bien précisé que c'était fonctionnel que dans certain cas, si je met des phrases avec du sens en plus c'est pas pour rien hein !

Sinon pour avoir une vision claire de comment pourrait fonctionner le DCPU il faut s'être penché dessus un jour où l'autre et j'espère que notch pensera bien cette partie.

De base une puce na rien. Pas même de bootloader c'est la première chose que l'on met dessus d'ailleurs. Mais ça a toujours une methode pour écrire dessus sans lancer et c'est bien normal, sinon on pourrait pas l'utiliser.

**Comment by L3nn0x** [comment]
J'ai travaillé avec des micropics et des cpu (en élec ^^). Bah les micropics sont programmables via une interface COM (ou usb), et après leur mémoire n'est plus changeable. Je pense que dans le cas du DCPU on est plutôt dans le cas d'un vrai CPU que d'un pic. Donc un secteur de boot écrit en ROM, et une "vraie" RAM. Plus les disquettes.

**Comment by Vaasref** [comment]
Dès lors que toute la RAM est intégrée au DCPU ont a plus un PIC qu'un CPU.

**Comment by L3nn0x** [comment]
Non, vu que le pic peut être éteint sans perte de la mémoire. C'est bien pour ça que c'est un pic et non un cpu.

**Comment by Vaasref** [comment]
Je parle pas tant de la puce en elle même que de la façon dont elle est gérée.
