### ISSUE TITLE
Branche clean_driverLEM

### ISSUE THREAD

**Issue by Vaasref** [FrOSt-Foundation/FrOSt#38]
Voila c'est pour une vérification, j'ai encore quelques modification à faire dessus, mais que du renommage donc vous pouvez vérifier.

**Comment by Yamakaky** [comment]
t'a pas oublié un `set PC, POP` dans m35fd_init ?

**Comment by Vaasref** [comment]
Je te parle du foutu driverLEM moi.

Retourne te coucher. Ça t'éviteras de dire des énormités.

**Comment by Yamakaky** [comment]
MERDE ! Vu que tu as lancé l'autre branche, j'ai pas lu le titre completement.

**Comment by Vaasref** [comment]
J'ai demander une vérification pas, un viandage complet parce que hâtif. Surtout que t'as même pas compris mon m35fd_init.

**Comment by Yamakaky** [comment]
Si on part comme ça, ton set PC ne set à rien…

**Comment by Vaasref** [comment]
Ça sert à être plus clair et comme je vais certainement remanier la partie détection/init de hw ça sera peut-être utile. Donc comme je me le sent de le faire aujourd'hui, bah faut laisser.

Sino si tu veux commenter ou questionner le/sur code de quelqu'un et que ce quelqu'un est manifestement là tu peux aller sur jappix hein.

**Comment by Yamakaky** [comment]
fc45f937d723df6f47b5dc4833e5d1e2c6dd1183
