### ISSUE TITLE
N'est-il pas naturel de pouvoir tout faire dans un vaisseau ?

### ISSUE THREAD

**Issue by Vaasref** [FrOSt-Foundation/FrOSt#39]
Personnellement j'aime être autonome, surtout si je suis isolé par des années-lumières si ce n'est des UA de l'endroit envers lequel je suis dépendant.

Donc franchement estimez vous encore correct de ne pouvoir supportez qu'un seul et unique lecteur de disquette ce qui rend impossible la copie d'une disquette en moins de 12-13 mise en cache des données, et ainsi 24-26 manipulations de disquette ?

**Comment by Yamakaky** [comment]
Bah non, faut juste l'implémenter ^^

**Comment by Vaasref** [comment]
C'est ultra simple en plus.

Une statique par type, un sélecteur par driver et le compte est bon.

> Sinon c'est moi où j'ai presque fait en une nuit plus que certain en totalité ?

Là ou il y a un semblant de difficulté et encore c'est pour la gestion des buffers multiples. Faut faire un gestionnaire de buffers. Le seul truc que je trouve beurk c'est que ça va se régler au malloc tout ça.

**Comment by Vaasref** [comment]
Je m'en occupe d'est que tout les drivers sont cleané et les branches mergées.
