### ISSUE TITLE
Branche clean_driverKeyboard

### ISSUE THREAD

**Issue by Vaasref** [FrOSt-Foundation/FrOSt#40]
Voila, alors j'ai pas forcément bien compris tellement c'était difforme mais ça a compilé et ça fonctionnait, donc c'est que j'ai du cleaner correctement.

Je me doute que j'ai du enlever ce que @FaerieFrOSt appellerait une "optimisation critiiiique" pour ce qui est de l'ex-injustement nommé waitKey, mais comme c'est qu'un doute Si c'était réellement une optimisation faut juste rajouter ça après : 

> ; return C
> :keyboard_getNextPressedKey_noPush
>   set A, 1
>   hwi [id_keyboard1]
> 
>   set PC, POP

Et ajouter le "_noPush" après le reste dans le interrupt handler ligne 192

Sinon vous pouvez merger après vérification.

**Comment by Yamakaky** [comment]
Fait !
25725ba41bd1afc406b3e9cf80b3200f4955843d
