### ISSUE TITLE
Programme natif VS programme importé ? "VS" vraiment ?

### ISSUE THREAD

**Issue by Vaasref** [FrOSt-Foundation/FrOSt#42]
Pour certain les programmes lancé sur un DCPU avec FrOSt ne peuvent être que des programmes importé, utilisant une interface à base d'interruptions.

Certes ça fonctionnera certainement très bien.

Mais je pense que c'est une vision trop software des choses. on a pas une bête de course, on a une machine qui ne me semble pas adaptée.

Pour revenir à la personne que je vise tout particulièrement, comme tu l'avais deviner toi Faerie tu dis vouloir un OS rapide léger et optimisé mais tu me parle après d'utilisateur comme si c'était un cornichon.

On peut pas faire à la fois optimisé et grand publique, c'est connu. Pas en même temps tout du moins.

Ou je veux en venir ? Eh bien je veux en venir au fait qu'il serait selon moi efficace de baser l'OS sur le système de stockage par disquette.

Ce que je veux dire c'est que nous avons un OS, très bien, mais plus lent qu'un programme spécialisé. Pourquoi ne pas bénéficier des deux ? Donnez la possibilité au programmeur de soit bénéficier de modules issus directement de notre travail tout en gardant les possibilités dans la flexibilité offertes par l'OS ?

Ce que je propose c'est de fractionner l'OS en parties opérantes et utiles. Les drivers pour commencer, ce que j'appel un programme natif (utilisant du code de l'OS et non une interface) pourra alors chercher les modules dont il a besoin pour les charger, et les utiliser sans avoir besoin d'avoir tout l'OS sans avoir non-plus besoin de les implémenter.

Ainsi à la fin du programme l'OS sera a nouveau rechargé dans la RAM pour repartir sur autre chose.

Et pour finir l'avantage pour le développeur est multiple, il peut utiliser un ou des modules ou non, ce qui lui permet d'adapter sont code extrêmement facilement.

**Comment by L3nn0x** [comment]
Le seul problème c'est qu'il n'existe pas de MMU. Donc du coup, toutes les adresses sont absolues. Donc c'est la mort dès que tu veux accéder à une fonction de l'OS directement, sans devoir recompiler ton programme avec l'OS. C'est pour ça que je propose les int pour gagner en flexibilité. Ok on perd en vitesse, mais d'in autre côté, c'est tellement plus simple.

**Comment by Vaasref** [comment]
C'est justement ce que je dis de compiler les programme avec les parties de l'OS qui sont intéressante, et c'est donc pourquoi selon moi il faut mettre le maximum de chose defines, statiques là ou ça a du sens, c'est à dire là ou leur utilisation prend racine.

Enfin de faire un maximum du standalone quoi.

**Comment by L3nn0x** [comment]
Oui, mais alors on perd l'avantage de l'OS multi-fonctions.

**Comment by Vaasref** [comment]
Non, on gagne les avantages d'un bootloader.

L'OS reste présent sur la disquette, donc si le programmeur voulait d'un OS il aurait pu simplement qu'il a pas voulu.

En faisant ça on ne bride en rien l'OS on ne fait que lui permettre de faire fonctionner une autre frange de programme. donc c'est du bénéfice net.

**Comment by L3nn0x** [comment]
Le problème c'est que notre OS n'est pas vraiment adapté au chargement par modules. Ça implique des changements majeurs dans notre architecture.

**Comment by Vaasref** [comment]
Bah ça dépends des modules, mais c'est possible de le faire en quelques variables statiques.

Je parle pas de charger l'OS par module
Je parle de charger des modules d'OS ayant des fonctions spécifiques et indépendantes.

**Comment by L3nn0x** [comment]
Donc d'avoir un noyau modulaire et non monolithique. C'est quand même vachement plus complexe.

**Comment by Vaasref** [comment]
C'est pas complexe de mettre des adresse de fin et de début de module, non.

**Comment by L3nn0x** [comment]
Faut pouvoir charger les modules. En plus, ils peuvent être théoriquement n'importe où dans la mémoire, donc ça complexifie encore plus la chose. Je parle même pas de la compilation des dits modules, qui est à faire séparément, et du passage obligé d'un MMU software sur chaque module chargé.

Un OS modulaire est vraiment compliqué. D'ailleurs, peu(très peu même) d'OS actuels le sont. Pour le peu de gain obtenu à charger les modules séparément, c'est mieux de se concentrer sur un noyau monolithique.
