### ISSUE TITLE
Branche lib_SPEDManager

### ISSUE THREAD

**Issue by Yamakaky** [FrOSt-Foundation/FrOSt#43]
Que devient-elle ?

**Comment by Vaasref** [comment]
Elle est normalement fonctionnelle, Mais j'attendais le merge de adding_testprog, pour pouvoir merge indev dans lib_SPEDManager pour pouvoir tester la lib.

**Comment by Yamakaky** [comment]
C'est déjà fait ^^

**Comment by Vaasref** [comment]
Qu'est-ce qui est déjà fait ? Si tu parle du merge de adding_testprog je suis au courant, si tu parle du test, bah si ça marche on peut merge.

**Comment by Yamakaky** [comment]
adding -> indev : fait
indev -> lib_SPED : pas fait
test : pas fait
