### ISSUE TITLE
Branche consoleAmelio

### ISSUE THREAD

**Issue by Yamakaky** [FrOSt-Foundation/FrOSt#45]
Que devient-elle ?

**Comment by L3nn0x** [comment]
Bah je compte continuer à ajouter des améliorations pour la console, mais j'ai pas trop d'idées pour l'instant...

**Comment by Yamakaky** [comment]
concrètement, elle est mergeable ?
Ça permet de prendre en compte les mises à jour effectuées dans les dev futurs

**Comment by L3nn0x** [comment]
Concrètement, je crois bien. Il me semble que tout était bon, bien que "salement" (comme diraient certains) codé.

**Comment by Yamakaky** [comment]
Alors je merge.

f1fa06b2409003223e127db8f3c49aa6335a4be4
