### ISSUE TITLE
L'ultra classe

### ISSUE THREAD

**Issue by Vaasref** [FrOSt-Foundation/FrOSt#47]
Un afficheur de LEM1802 sur SPED-3.

Ça nécessite juste un buffer de 0xC000 mots, c'est jouable !

Par contre il faut pas utiliser les 1m de largeur du SPED-3 parce que la densité c'est deux traits part pixel pour que la largeur soit en accord avec la hauteur ce sera tout petit.

Sinon ya une autre méthode qui est de dessiner le contour des lettre avec une 40aine de points par lettre max on arrive à 15 360 mots utilisé pour le buffer au max, soit 25 600 au final ev embarquant la base de donné des lettres. Et pour le coup il est possible d'afficher 2 écran.
Après tout est question de densité, j'ai pas cherché a trouver le nombre minimum de points pour afficher la police par défaut sans compter les caractères spéciaux tout brouillé, mais du coup je pense que ça pourrait facilement augmenter de 4 le nombre d'émulateur de LEM1802 tout en gardant une marge correcte.

Et puis si on passe l'émulation de lem ça fait un écran super grand avec plein de caractères, si l'optimisation de la mémoire un un peu poussée on peut aussi économiser de la place en mettant swappant avec des tables de caractères sur des disquettes. Avec un peut de change ya peut-être moyen de faire un affichage de 3x3 lem ce qui donne une résolution gros pixels de 96x72

**Comment by Yamakaky** [comment]
T'es malade ^^

**Comment by Vaasref** [comment]
On a des jouets sympas autan les utiliser.

**Comment by L3nn0x** [comment]
Pourquoi pas, je demande à voir. :p 
Malheureusement, je suis trop mauvais dans ce domaine pour être d'une quelconque aide...
