### ISSUE TITLE
Branche clean_driver SPC2000

### ISSUE THREAD

**Issue by Vaasref** [FrOSt-Foundation/FrOSt#48]
Bon c'est le dernier driver, il est très abstrait puisqu'on ne peux pas l'utiliser, mais c'est pourtant un très bon senseur, il permet de détecter les trous noir, une rotation trop rapide un manque de carburant. Branche à vérifier et merger.

Il faudrait faire un driver généraliste qui servirait à collecter toute les information issues du HW, sans même avoir des capteurs fait pour capter, on pourra déjà avoir une carte de l'étendue des dégâts, et puis pour la suite on pourra mettre tout les drivers de capteurs dedans.
Vous approuvez ?

**Comment by L3nn0x** [comment]
Bah on a déjà un peu ça techniquement. C'est pas géré par un driver, mais plutôt par l'interrupt handler. :)
