### ISSUE TITLE
[FS] VSF : Very Singular Filesystem

### ISSUE THREAD

**Issue by Vaasref** [FrOSt-Foundation/FrOSt#49]
VFS WIP
Post WIP
# Le Very Singular Filesystem

Trois types de disquettes : 
0. ONESHOT (J'aime bien le nom, ça fait classe B] )
1. SECTOR
2. FILE

Le flag est en tout début de disquette au premier mot. Une disquette ayant tout à 0 sera donc considérée comme une oneshot.
## 0. Le type "Oneshot"

Le plus simple de tous au niveau gestion puisqu'il n'est pas géré par le VSF, ce type étant basique il est géré directement par le programme via le driver.

Comme sa gestion n'est pas faite pas le VSF il peut être utilisé pour d'autres FS.

Une disquette de swap sera forcément une "Oneshot"
## 1. Le type "Sector"

On traite les données par secteurs considérant un fichier comme un ou plusieurs secteurs, ce qui engendre beaucoup de perte de place mais qui est bien plus rapide que le type "File" et plus simple et gérer par le programme que le type "Oneshot"
### Le système d'état

Dans ce type on utilise le premier secteur comme tableau pour connaitre l'état des autres secteurs.

L'état d'un secteur sert à savoir si celui-ci est libre, occupé, ou fragment d'une suite de secteurs. Il permet aussi la protection spécifique d'un secteur ou d'une suite de secteur.

L'état d'un secteur est stocké sur 4 bits pour faire tenir dans les 511 mots du premier secteurs les états des 1439 autres secteurs.
#### Les états sont :
- 0 Secteur libre
- 1 Secteur non relié
- 2 Secteur non relié et protégé
- 3 Secteur relié initial
- 4 Secteur relié initial et protégé
- 5 Secteur relié
- 6 Secteur relié et protégé
  Le premier bit sert donc à savoir si le secteur est protégé ou non.
### Les adresses

On accède donc aux données avec une adresse allant de 0 à 1438 ce qui tient dans 16bits.

Le comportement des fonctions si une adresse pointe sur une suite de secteur mais pas au premier secteur de cette suite, sera de trouver le premier secteur 
#### Lecture

Lit le secteur d'adresse donnée, un second paramètre sert à connaitre le nombre de secteur prévu par l'utilisateur, si le nombre de secteur prévu n'est pas suffisant la fonction renvoi une erreur
- Nombre d'entrées : 3
- Nombre de sorties : 1
#### Ecriture

Ecrit à l'adresse donnée un nombre donné de secteur, si le quatirème paramètre est différent de 0 alors on l'utilise pour connaitre le nombre de mots à écrire.
À noter qu'une écriture d'un nombre de mots donné n'effacera pas la place non utilisée du dernier secteur.
- Nombre d'entrées : 4
- Nombre de sorties : 1
#### Ajout

Même comportement que pour l'écriture, la fonction va simplement chercher le premier espace avec assez de place pour écrire dans un ou plusieurs secteurs.
- Nombre d'entrées : 3
- Nombre de sorties : 1
#### Autres

D'autres fonctions utiles seront ajoutées, protection/de-protection, check de protection, effaçage de secteur.
## 2. Le type "File"

Ce dernier type traite la disquette comme une suite linéaire de mots, contenant une suite de fichiers. Il permet ou non de donner un nom à un fichier.

Aucune fragmentation. Aucun trou de mémoire libre. Pas de dossiers. Nécessité d'un lecteur en swap pour certaines opérations (déplacement, extension et suppression pour commencer).

Ce type est plus lent dans son utilisation et bien plus lent dans sa gestion que le type "Sector" mais il est bien plus pratique pour l'utilisateur, puisque plus lisible grâce aux noms de fichiers.

En plus d'être plus lente la gestion doit être plus réfléchie : modifier la taille d'un fichier impliquera pour le logiciel de déplacer tout les fichier après celui-ci.
Ainsi pour garder un système le plus performant possible les fichiers doivent être placé du plus statique au plus dynamique dans l'index

Dans le contexte qui est le notre, les fichiers ne sont pas sensés bouger beaucoup, tout ce qui est contingent n'est pas réellement à destination du DCPU, donc nous n'avons pas beaucoup de médias à gérer, sans média pas de besoin d'autre chose qu'un système simple orienté sur les données statiques. Si un programme veut utiliser une disquette pour avoir une utilisation très intense il n'a pas besoin d'un système de fichier.

**Comment by Yamakaky** [comment]
Je vais mettre mes remarques au fur et à mesure de ma lecture

Oneshot : 
tiens, du swap, pas con, faudrait l'implémenter, en coordination avec le 'MMU'.
Le problème du mot magique de 0 pour la oneshot, c'est que ça la différencie pas d'une disquette vide ^^. Faudrait utiliser 2-3 mots avec des valeurs précises.

Secteur : 
Pour ce FS, tu prend en compte que le programme connait en dur les secteurs à charger ?
Lecture : J'ai pas très bien compris à quoi sert le deuxième paramètre, c'est le nombre de secteurs à lire ?
Ecriture + lecture :  tu semble avoir oublié de mettre un paramètre pour l'adresse RAM où écrire/lire

File : 
Effectivement, si ce ne sont que des données statiques, ça peut donner de bonnes perfs. Par contre, pas mal de fichiers seront à cheval sur deux secteurs, d'où un surcout au chargement.

En fait, c'est pas un FS, ce sont 3 FS ^^
Ah, et il vaudrait mettre cette spec dans fs/

**Comment by Vaasref** [comment]
C'est branché simplement que je push pas avant d'avoir un truc correct (déjà que je commit pas avant d'avoir un truc correct non plus).

Oui pour la lecture j'avais oublié un paramètre, comme j'avais penser à la longueur après.
Alors pour t'expliquer pourquoi un paramètre de longueur prévu, c'est simple, tu prévois 512 mots, donc un secteur, très bien, mais si tu tombe sur une chaîne de secteur, bah voila ça écrit après l'espace prévu et c'est caca.
Sinon je peux rajouter à la lecture un paramètre de longueur comme pour l'écriture, qui permettrait de faire une lecture linéaire, ce qui serait plus pratique.

Et non pour l'écriture il y a bien 4 param, 1 adresse sur disquette 2 adresse RAM, 3 nombre de secteurs, 4 taille si != 0

Après j'ai pas encore fait cette partie, mais je peux aussi dupliquer les fonction pour faire une avec lecture linéaire et une lecture secteur. puisque de toute façon le dernier paramètre écrase l'ancien si ce premier (et donc le dernier des paramètres) est set à autre chose que 0.

**Comment by Yamakaky** [comment]
Je parlais de la spec, pas de l'implémentation, comme pour fsf.

**Comment by L3nn0x** [comment]
Je vous laisse décider, c'est pas vraiment mon point fort les fs...

**Comment by Vaasref** [comment]
C'est moins utile de savoir comment ça marche que comment on le fait marcher, puisqu'il sera plus difficile de comprendre comment le faire marcher que comment ça marche.

**Comment by Yamakaky** [comment]
Je vois pas le problème, il faut les deux. Imagine que tu partes du projet (ce qui est le cas de 70% de l'équipe originelle ^^), ce serait con d'avoir un code qu'on pourrait difficilement modifier car on saurait pas comment il fonctionne. Autant avoir une API d'utilisation et une spec sur le fonctionnement interne.

**Comment by Vaasref** [comment]
Ce que je veux dire, c'est que la spécification est insignifiante par rapport à la notice, niveau taille et sens.

Ce que je veux dire c'est qu'écrire une spécification dénuée d'utilisation est inutile, une spécification n'a de sens que avec l'application qui va avec.

Comprends donc que t'as pas besoin de spécification pour le VSF

**Comment by Yamakaky** [comment]
C'est ce que je dis, il faut les deux au final.

**Comment by Vaasref** [comment]
Useless.

Maintenant attends de voir le final.

**Comment by Yamakaky** [comment]
En fait, tu le vois comme un truc en une version, tu donnes ton travail et tout va bien. Personnellement, la spec m'intéresse plus que l'implémentation, alors la mettre sur git (avec une gestion des versions donc) me parait plus logique. (oui, j'ai du mal à finir mes phrases)

**Comment by L3nn0x** [comment]
Mais de toute façon, il faut bien savoir ce qui est possible de faire avec, vu qu'on va ensuite implémenter un vfs. :)
