### ISSUE TITLE
Translation of the wiki needed

### ISSUE THREAD

**Issue by azertyfun** [FrOSt-Foundation/FrOSt#53]
As of now, only a few of the wiki pages are in English.

**Comment by neogoo123** [comment]
Working on this now.. Not the best french speaker, but might as well help out where I can.

**Comment by L3nn0x** [comment]
That's really cool of you, thank you very much for your help :)

**Comment by neogoo123** [comment]
My pleasure! I've been learning french, so this will just help out that much more :D

**Comment by L3nn0x** [comment]
It's great :) I've seen a few typo here and there, but French is really hard and even we can have a hard time with it...
Thanks a lot, it definitely helps to transition from full French to English.

**Comment by neogoo123** [comment]
:) Just doing what I can. Hopefully will finish translations tonight, but feel free to contact me if you need anything :D

**Comment by L3nn0x** [comment]
No problem, right now we are kinda reworking the design of the OS, its purpose and how we are going to adapt/create/delete functionalities to Techcompliant. A lot of thinking process that doesn't necessarily show on the outside. If you wanna help out a bit more, you could always go through the code (in the indev branch), I don't quite remember if we replaced all of the french comments in there or not :)

**Comment by neogoo123** [comment]
Alrighty, I might take a look through when I'm done translating the wiki.

**Comment by neogoo123** [comment]
Done, can we remove this issue?

**Comment by L3nn0x** [comment]
Thanks a lot :)
