### ISSUE TITLE
Man.

### ISSUE THREAD

**Issue by L3nn0x** [FrOSt-Foundation/FrOSt#6]
Voulez vous une commande man ?

Intérêt : pas énorme, surtout s'il y a un manuel de fournit.
Désavantage : prend beaucoup de place dans la mémoire.

Votre avis ?

**Comment by Yamakaky** [comment]
Je pense qu'on peut s'en passer, on a déjà pas beaucoup de place... Après on peut toujours faire un fichier spécial à mettre sur un disque à part, mais ça fait un disque en moins. A mon avis, une bonne doc sur le site/github suffit

**Comment by L3nn0x** [comment]
Ok, donc on oublie man.

**Comment by Yamakaky** [comment]
L'idée est bonne, mais l'implémentation serai trop lourde. À nous de produire une doc hors-ligne de qualité !
