### ISSUE TITLE
Quelle(s) touche(s) utiliser ?

### ISSUE THREAD

**Issue by L3nn0x** [FrOSt-Foundation/FrOSt#7]
Je propose, pour changer d'écran virtuel, d'utiliser f1,f2,f3 et f4 (si elles fonctionnent). On aura pour l'instant 4 bureaux virtuels au maximum, donc ça me paraît pas mal.

Des suggestions ?

**Comment by Yamakaky** [comment]
Elles fonctionnent pas, dommage, c'était une bonne idée

**Comment by azertyfun** [comment]
[déterrage]Ben on peut utiliser alt+1, shift + 1 ou un truc comme ça ^^[/déterrage]

**Comment by L3nn0x** [comment]
Bonne idée, je viens d'y penser en fait... :p
