### ISSUE TITLE
Conflit dans les gestionnaires de périphs

### ISSUE THREAD

**Issue by earth75** [FrOSt-Foundation/FrOSt#8]
Il y en a tout simplement deux, un dans kernel et un dans Boot. je propose de supprimer celui du kernel parce qu'il est moins avancé. C'est pas vraiment qu'il y en ait deux qui me gène c'est que ce sont quasiment les meme ils partagent dailleurs les memes labels.... on dirait un copier collé qui a foiré.

**Comment by Yamakaky** [comment]
Ouais, on dirait ^^

On a lancé un nouveau système de périph, alors peut-être que l'autre est resté.
As-tu vu la branche raw-dev-unstable ? C'est dessus que Faerie met les derniers trucs

**Comment by L3nn0x** [comment]
Oui, c'est exactement ce qui s'est passé. Mais c'est de l'histoire ancienne dans la branche la plus mise à jour...
