### ISSUE TITLE
[pop] n'existe pas !

### ISSUE THREAD

**Issue by Yamakaky** [FrOSt-Foundation/FrOSt#9]
e4b4d24df6cf1aaf30b31be3c472adfee518d1bc

**Comment by L3nn0x** [comment]
Oups, c'est où ?

**Comment by Yamakaky** [comment]
… Et le lien vers le commit, il sert à rien ?

**Comment by L3nn0x** [comment]
Tiens donc, j'avais pas vu... :p

**Comment by Yamakaky** [comment]
Corrigé
71f980e325b898fcea2fe96a5d0bfbf139581b32
